# Generated by Django 5.2.4 on 2025-07-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroP', '0002_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
